from __future__ import annotations

import argparse
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def build_method_draft() -> str:
    lines: list[str] = []
    lines.append("# ReferGaussian Method Draft")
    lines.append("")
    lines.append("## 1. Problem Setup")
    lines.append("")
    lines.append(
        "We consider dynamic novel-view synthesis from calibrated monocular or multi-view videos. "
        "Given a camera observation at time `t`, vanilla 4DGS represents scene dynamics mainly by feeding `t` into a deformation module while keeping the Gaussian primitive itself essentially spatial."
    )
    lines.append("")
    lines.append(
        "ReferGaussian changes this design choice. Our goal is not only to learn a better temporal conditioning function, but to turn each Gaussian into a **local spacetime primitive** with explicit temporal support, local motion, and downstream trajectory-aware semantics."
    )
    lines.append("")
    lines.append("## 2. Method Overview")
    lines.append("")
    lines.append("For each Gaussian `i`, we augment the standard spatial parameters with temporal state:")
    lines.append("")
    lines.append("`Theta_i = {mu_i, Sigma_i, alpha_i, f_i, a_i, s_i, v_i, u_i}`")
    lines.append("")
    lines.append("where:")
    lines.append("")
    lines.append("- `mu_i, Sigma_i, alpha_i, f_i` are the canonical center, covariance, opacity, and appearance parameters.")
    lines.append("- `a_i` is a temporal anchor.")
    lines.append("- `s_i` is a temporal support scale.")
    lines.append("- `v_i` is a first-order temporal velocity.")
    lines.append("- `u_i` is a second-order temporal acceleration.")
    lines.append("")
    lines.append("Our method is built from three layers:")
    lines.append("")
    lines.append("1. `temporal warp`: learn a local time reparameterization before deformation.")
    lines.append("2. `spacetime primitive`: make time part of the Gaussian support itself.")
    lines.append("3. `support-aware optimization`: make densification, cloning, splitting, pruning, clustering, and semantics depend on spacetime support statistics.")
    lines.append("")
    lines.append("## 3. Temporal Warp")
    lines.append("")
    lines.append("We first allow the model to replace raw time `t` with a learned time coordinate:")
    lines.append("")
    lines.append("`tau_i = phi(t, c_i)`")
    lines.append("")
    lines.append("where `c_i` denotes local Gaussian context. In ReferGaussian, the most important case is the `stellar` warp, where `c_i` includes local temporal state and motion descriptors such as:")
    lines.append("")
    lines.append("- normalized spatial position,")
    lines.append("- temporal anchor and scale,")
    lines.append("- velocity and acceleration,")
    lines.append("- motion magnitude statistics.")
    lines.append("")
    lines.append("This layer is still a **temporal parameterization module**, not yet a new primitive. It changes how each Gaussian measures local time, but by itself it would still be close to a strong 4DGS-style temporal conditioning model.")
    lines.append("")
    lines.append("To keep the warp well-posed, we regularize it with:")
    lines.append("")
    lines.append("- a monotonicity term,")
    lines.append("- a smoothness term,")
    lines.append("- a slope-budget term to avoid pathological compression or stretching of time.")
    lines.append("")
    lines.append("## 4. Spacetime Gaussian Primitive")
    lines.append("")
    lines.append("The main departure from vanilla 4DGS starts when temporal support is written directly into each Gaussian.")
    lines.append("")
    lines.append("For a query time `t`, we define:")
    lines.append("")
    lines.append("`Delta t_i = t - a_i`")
    lines.append("")
    lines.append("`g_i(t) = exp(-0.5 * beta * (Delta t_i / s_i)^2)`")
    lines.append("")
    lines.append("`d_i(t) = v_i * Delta t_i + 0.5 * u_i * Delta t_i^2`")
    lines.append("")
    lines.append("where `g_i(t)` is a temporal visibility/support gate and `d_i(t)` is the local worldline drift.")
    lines.append("")
    lines.append("The rendered center therefore becomes:")
    lines.append("")
    lines.append("`mu_i(t) = mu_i + lambda_d * d_i(t)`")
    lines.append("")
    lines.append("This already differs from 4DGS at the primitive level: time is no longer only an input to deformation, but part of the primitive support itself.")
    lines.append("")
    lines.append("## 5. Weak Tube Approximation")
    lines.append("")
    lines.append("As an intermediate step, we implement a weak spacetime tube variant (`stellar_tube`). Instead of explicitly expanding a Gaussian into multiple time samples, we estimate local tube moments around the current query time and convert them into an additional covariance term before rasterization.")
    lines.append("")
    lines.append("This gives a weak 4D support approximation while leaving the low-level rasterizer unchanged. It is useful as an engineering bridge, but it is still an approximation because one primitive is rasterized once per query time.")
    lines.append("")
    lines.append("## 6. Worldtube Rendering")
    lines.append("")
    lines.append("Our main geometry line is `stellar_worldtube`, where one parent Gaussian expands into multiple child samples along local temporal support.")
    lines.append("")
    lines.append("For each Gaussian `i`, we sample `K` local temporal segments around the anchor within a support span:")
    lines.append("")
    lines.append("`[Delta t^-_{ik}, Delta t^+_{ik}]`")
    lines.append("")
    lines.append("and use the segment center to define:")
    lines.append("")
    lines.append("`Delta t_{ik} = 0.5 * (Delta t^-_{ik} + Delta t^+_{ik})`")
    lines.append("")
    lines.append("`t_{ik} = a_i + Delta t_{ik}`")
    lines.append("")
    lines.append("`mu_{ik} = mu_i + v_i * Delta t_{ik} + 0.5 * u_i * E[Delta t^2]_{ik}`")
    lines.append("")
    lines.append("Each child sample receives a temporal weight formed from:")
    lines.append("")
    lines.append("- a local kernel over temporal offset,")
    lines.append("- the temporal gate `g_i`,")
    lines.append("- the local segment duration,")
    lines.append("- occupancy and visibility modulation.")
    lines.append("")
    lines.append("The final child weight is a normalized local density mass:")
    lines.append("")
    lines.append("`w_{ik} propto kappa(Delta t_{ik}) * g_i(t_{ik}) * l_{ik}`")
    lines.append("")
    lines.append("where `l_{ik}` denotes normalized support duration. In addition, child opacity and scale can be modulated by local occupancy and tangent-aligned motion magnitude.")
    lines.append("")
    lines.append("The rendered image is then produced by rasterizing the set of child samples while keeping optimization statistics attached to the original parent Gaussian. This is important: although rendering expands one primitive into multiple child samples, gradients and densification signals are still accumulated at the parent level, preserving compatibility with the upstream training loop.")
    lines.append("")
    lines.append("The current implementation keeps the CUDA rasterizer unchanged. Therefore `stellar_worldtube` should be understood as a **local spacetime integral approximation on top of a 3D rasterizer**, not yet a full 4D Gaussian rasterizer.")
    lines.append("")
    lines.append("## 7. Adaptive Temporal Support")
    lines.append("")
    lines.append("A central problem in explicit worldtube modeling is support allocation: if support is too small, dynamic structures collapse back to near-point behavior; if support is too large, the model degenerates into temporal blur.")
    lines.append("")
    lines.append("To address this, we define support statistics from motion magnitude, spatial extent, and visibility:")
    lines.append("")
    lines.append("- `base_support_i = s_i * span`")
    lines.append("- `base_drift_i = ||v_i|| * base_support_i + 0.5 * ||u_i|| * base_support_i^2`")
    lines.append("- `tube_ratio_i = base_drift_i / spatial_extent_i`")
    lines.append("")
    lines.append("We then adapt support using a target ratio and a visibility-aware correction factor:")
    lines.append("")
    lines.append("`support_factor_i = 1 + gamma * error_i * visibility_i`")
    lines.append("")
    lines.append("This gives an effective support:")
    lines.append("")
    lines.append("`effective_support_i = support_factor_i * s_i * span`")
    lines.append("")
    lines.append("These statistics are not only renderer diagnostics; they drive optimization and later entity-level grouping.")
    lines.append("")
    lines.append("## 8. Support-Aware Optimization")
    lines.append("")
    lines.append("Vanilla 4DGS densification and pruning are largely image-loss-aware. In ReferGaussian, once temporal support becomes part of the primitive, the optimization strategy must also become support-aware.")
    lines.append("")
    lines.append("### 8.1 Regularization")
    lines.append("")
    lines.append("We optimize a reconstruction objective with temporal support regularization:")
    lines.append("")
    lines.append("`L = L_rec + L_ssim + lambda_warp * L_warp + lambda_vel * L_vel + lambda_acc * L_acc + lambda_sup * L_sup + lambda_ratio * L_ratio`")
    lines.append("")
    lines.append("where:")
    lines.append("")
    lines.append("- `L_vel` regularizes velocity magnitude,")
    lines.append("- `L_acc` regularizes acceleration magnitude,")
    lines.append("- `L_sup` constrains effective support to remain within a valid range,")
    lines.append("- `L_ratio` constrains the tube ratio around a target regime.")
    lines.append("")
    lines.append("### 8.2 Activity-Aware Densification")
    lines.append("")
    lines.append("We define temporal activity from motion, support scale, anchor offset, and, in the worldtube case, support complexity. The densification score is then reweighted as:")
    lines.append("")
    lines.append("`score_i = ||grad_i|| * (1 + gamma_a * activity_i)`")
    lines.append("")
    lines.append("Thus short-lived but informative dynamic structures receive more protection than in purely image-gradient-based densification.")
    lines.append("")
    lines.append("### 8.3 Tube-Aware Split and Clone")
    lines.append("")
    lines.append("In baseline split/clone operations, new Gaussians typically inherit nearly identical temporal parameters. In ReferGaussian, when worldtube support is enabled, child Gaussians are initialized by shifting anchor and scale along temporal support and updating velocity consistently with local acceleration.")
    lines.append("")
    lines.append("This makes split/clone operations respect the current local worldtube rather than duplicating the same point-like temporal state.")
    lines.append("")
    lines.append("### 8.4 Support-Aware Pruning")
    lines.append("")
    lines.append("Pruning is also modified. Low-opacity Gaussians are not removed solely on the basis of opacity; we protect primitives with high temporal activity or sufficiently large tube-ratio statistics. This prevents short but semantically important dynamic events from being eliminated too early.")
    lines.append("")
    lines.append("## 9. Bootstrap Strategy")
    lines.append("")
    lines.append("Initialization is treated as **orthogonal** to the main method.")
    lines.append("")
    lines.append("ReferGaussian supports multiple bootstrap modes:")
    lines.append("")
    lines.append("- `random_init` for synthetic scenes without point clouds,")
    lines.append("- `dataset_ply` when a reliable dataset point cloud already exists,")
    lines.append("- `colmap` when a reconstructed multi-view point cloud is available,")
    lines.append("- `da3` when the scene lacks a reliable initial point cloud and a stronger feed-forward geometry prior is needed.")
    lines.append("")
    lines.append("DA3 is therefore not the main contribution. In our intended paper framing, it should remain an initialization ablation or a practical enhancement, not the core novelty claim.")
    lines.append("")
    lines.append("## 10. Entity Bank as the Semantic Interface")
    lines.append("")
    lines.append("The geometric output of ReferGaussian is not just a rendered video; it is also a reusable spacetime bank.")
    lines.append("")
    lines.append("From the optimized worldtube parameters, we sample per-Gaussian trajectories and export:")
    lines.append("")
    lines.append("- `trajectory_samples.npz`,")
    lines.append("- `tube_bank.json`,")
    lines.append("- `cluster_stats.json`,")
    lines.append("- `entities.json`.")
    lines.append("")
    lines.append("Each entity is formed by clustering Gaussians using support-aware features that include:")
    lines.append("")
    lines.append("- mean trajectory center,")
    lines.append("- displacement,")
    lines.append("- velocity and acceleration,")
    lines.append("- temporal anchor and scale,")
    lines.append("- occupancy, visibility, tube ratio, and effective support.")
    lines.append("")
    lines.append("This differs from semantics that are attached on top of unchanged splats: here, the grouping structure is derived directly from the spacetime support statistics of the primitive.")
    lines.append("")
    lines.append("## 11. Semantic Heads and Query Interface")
    lines.append("")
    lines.append("On top of the entity bank, ReferGaussian builds a semantic interface in stages:")
    lines.append("")
    lines.append("`entities -> semantic_slots -> semantic_tracks -> semantic_priors -> segmentation_bootstrap -> query grounding`")
    lines.append("")
    lines.append("The key architectural element is `semantic_priors`, which decomposes each entity into three geometry-grounded semantic channels:")
    lines.append("")
    lines.append("- `static semantics`: persistent scene parts and long-horizon support regions,")
    lines.append("- `dynamic semantics`: moving objects and motion-centric descriptions,")
    lines.append("- `interaction semantics`: short support windows and contact-like events.")
    lines.append("")
    lines.append("This decomposition is driven by support windows, motion ratio, occupancy evidence, and visibility evidence rather than by purely image-level heuristics.")
    lines.append("")
    lines.append("At query time, ReferGaussian can use either:")
    lines.append("")
    lines.append("- a strong external semantic backend through `TRASE bridge`, or")
    lines.append("- a native query path built on its own semantic priors and support-aware tracks.")
    lines.append("")
    lines.append("At the current stage, the bridge backend is more stable than the native one, but the architecture is already set up so that semantic grounding is defined over worldtube support and entity trajectories.")
    lines.append("")
    lines.append("## 12. Relation to Vanilla 4DGS")
    lines.append("")
    lines.append("The difference between ReferGaussian and vanilla 4DGS should be stated at three distinct levels.")
    lines.append("")
    lines.append("### 12.1 Time Parameterization")
    lines.append("")
    lines.append("- 4DGS: time is mainly a conditioning input.")
    lines.append("- ReferGaussian: time can first be reparameterized locally through `phi(t, c_i)`.")
    lines.append("")
    lines.append("### 12.2 Primitive Definition")
    lines.append("")
    lines.append("- 4DGS: a Gaussian is still essentially a 3D primitive queried at time `t`.")
    lines.append("- ReferGaussian: a Gaussian has explicit local temporal support, motion, and, in the worldtube case, expands into a local spacetime tube during rendering.")
    lines.append("")
    lines.append("### 12.3 Optimization and Downstream Interface")
    lines.append("")
    lines.append("- 4DGS: densification and pruning are primarily image-loss-aware; semantics are typically external or loosely attached.")
    lines.append("- ReferGaussian: support-aware statistics affect optimization, clustering, and the semantic interface itself.")
    lines.append("")
    lines.append("Therefore, the paper claim should not be phrased as “we use a better time encoding for 4DGS.” The stronger and more accurate claim is:")
    lines.append("")
    lines.append("**ReferGaussian turns dynamic Gaussians from time-conditioned spatial splats into support-aware spacetime worldtubes, and uses their support statistics to drive both optimization and entity-level semantic grounding.**")
    lines.append("")
    lines.append("## 13. Recommended Paper Framing")
    lines.append("")
    lines.append("If the method is written as a paper, the cleanest framing is:")
    lines.append("")
    lines.append("- Main contribution: `worldtube primitive + support-aware optimization`.")
    lines.append("- First downstream contribution: `trajectory-aware entity bank`.")
    lines.append("- Second downstream contribution: `support-grounded static/dynamic/interaction semantic priors and query grounding`.")
    lines.append("- Orthogonal component: `DA3 bootstrap` as a practical initialization option rather than the core method.")
    lines.append("")
    lines.append("## 14. Code Mapping")
    lines.append("")
    lines.append("- Temporal warp: `refergaussian/temporal/modules.py`, `refergaussian/temporal/warp_io.py`")
    lines.append("- Spacetime primitive and worldtube support: `external/4DGaussians/scene/gaussian_model.py`")
    lines.append("- Render-time worldtube expansion: `external/4DGaussians/gaussian_renderer/__init__.py`")
    lines.append("- Training losses and warp regularization: `external/4DGaussians/train.py`")
    lines.append("- Entity bank export: `refergaussian/entitybank/export.py`, `refergaussian/entitybank/tube_bank.py`")
    lines.append("- Semantic pipeline: `refergaussian/semantics/*.py`")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "reports/refergaussian_method_draft.md"),
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_method_draft(), encoding="utf-8")
    print(output_path)


if __name__ == "__main__":
    main()
